name: Bug Report
description: Report a defect or regression with concrete reproduction evidence.
title: "[Bug]: "
labels: ["type:bug", "status:needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Provide specific evidence. Include file paths/lines, logs, or failing tests when possible.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-sentence problem statement.
      placeholder: Sprite drag-drop creates entity but does not assign texture.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Deterministic steps to reproduce.
      placeholder: |
        1. Open editor
        2. Drag texture into viewport
        3. Observe created sprite has no texture
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What currently happens.
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: File paths + line ranges, logs, test output, or screenshots.
      placeholder: |
        - apps/editor/panels/ViewportPanel.cpp:205-209 (TODO comment)
        - editor.log excerpt...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority:P1-important
        - priority:P0-crash-blocker
        - priority:P2-later
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: Area Label
      description: Use one or more `area:*` labels.
      placeholder: area:editor-tools
    validations:
      required: true

  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      description: Concrete acceptance criteria.
      placeholder: |
        - Fix implemented
        - Regression test added
        - Verified on target platforms
    validations:
      required: true
